name: "Twenty Twenty-Five"
description: "A clean, minimalist theme inspired by WordPress Twenty Twenty-Five with fluid typography and spacing."
author: "Railspress"
version: "1.0.0"
license: "MIT"
homepage: "https://wordpress.org/themes/twentytwentyfive/"





